### ISSUE TITLE
Error when running commands

### ISSUE THREAD

**Issue by cgcardona** [bigearth/bitbox-cli#1]
Getting the following error when I install from npm. It's not properly bundling the dependencies before deploying to npm.

```
module.js:557
    throw err;
    ^

Error: Cannot find module 'commander'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/carloscardona/.nvm/versions/node/v9.4.0/lib/node_modules/bitbox-cli/index.js:2:15)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
```

**Comment by cgcardona** [comment]
Solved
